#%RAML 1.0
---
title: Mobile Payments
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: application/json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/mobile/payments:
  /banks:
    get:
      displayName: Get a list of available banks
      description: This endpoint retrieves a list of banks for the user to select from to make a payment
      is: [headers.acceptHeader]
      (annotations.scope): "read:native-apps-api-orchestration"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:native-apps-api-orchestration" ] } ]
      queryParameters:
        journeyId:
          type: string
          example: 27085215-69a4-4027-8f72-b04b10ec16b0
          required: true
      responses:
        200:
          body:
            application/json:
              examples:
                example-1:
                  value: !include examples/get-banks-response-example.json
  /payments:
    /{sessionDataId}:
      get:
        displayName: Get the payment status
        description: This endpoint retrieves a status of a payment associated with a session
        is: [headers.acceptHeader]
        (annotations.scope): "read:native-apps-api-orchestration"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:native-apps-api-orchestration" ] } ]
        uriParameters:
          sessionDataId:
            description: The ID associated with the payment session.
            type: string
            example: 51cc67d6-21da-11ec-9621-0242ac130002
            required: true
        queryParameters:
          journeyId:
            type: string
            example: 27085215-69a4-4027-8f72-b04b10ec16b0
            required: true
        responses:
          200:
            body:
              application/json:
                examples:
                  example-2:
                    value: !include examples/get-payment-status-response-example.json
  /payments:
    post:
      displayName: Creates a payment
      description: This endpoint initiates an open banking payment and returns a payment URL.
      is: [headers.acceptHeader]
      (annotations.scope): "read:native-apps-api-orchestration"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:native-apps-api-orchestration" ] } ]
      body:
        application/json:
          example:
            example-3:
              value: !include examples/post-payment-request-example.json
      queryParameters:
        journeyId:
          type: string
          example: 27085215-69a4-4027-8f72-b04b10ec16b0
          required: true
      responses:
        200:
          body:
            application/json:
              examples:
                example-4:
                  value: !include examples/post-payment-response-example.json